# Middleware merupakan namagrup
# jika disertakan middleware dengan nama grup admin
# maka data tersebut hanya bisa diakses oleh admin
# tapi jika ingin lebih dari satu grup yang dapat mengakses
# anda bisa menambahkan koma (,) misal admin,user
# maka route tersebut bisa diakses oleh grup admin dan user

    

# Route Admin
# route dengan awalan admin akan membaca controller di folder backend
admin:
  path:
    /admin: 
      method: get
      controller: HomeController
      function: index
      middleware: admin,user
    /admin/pengaturan: 
      method: get
      controller: PengaturanController
      function: index
      middleware: admin,user
    /admin/editor: 
      method: get
      controller: EditorController
      function: index
      middleware: admin,user
  



# Route Website
# route akan membaca controller di folder frontend
website: 
  path: 
    /: 
      method: get
      controller: HomeController
      function: index


# Route Api
# route akan membaca folder service api 
service: 
  path: 
    /api/test: 
      method: get,post
      controller: TestService
      function: load



# Route Tester
test: 
  path: 
    /test: 
      # Jika ingin menambahkan method di route yang sama misalkan /test
      # maka tambahkan dengan pisah koma (,)
      # contoh : method: get,post 
      # hal itu berlaku juga untuk function jika ingin lebih dari satu
      # maka contohnya function: index,post
      # jika methodnya terdapat dua method dan functionnya satu maka akan
      # mengarah ke satu function yang sama
      method: get,post
      controller: TestController
      function: index,post
    /test/do/:params: 
      method: get
      controller: TestController
      function: index
