# Middleware merupakan namagrup
# jika disertakan middleware dengan nama grup admin
# maka data tersebut hanya bisa diakses oleh admin
# tapi jika ingin lebih dari satu grup yang dapat mengakses
# anda bisa menambahkan koma (,) misal admin,user
# maka route tersebut bisa diakses oleh grup admin dan user

    

# Route Admin
admin:
  path:
    /admin: 
      method: get
      controller: HomeController
      function: index
      middleware: admin,user



# Route Website
website: 
  path: 
    /: 
      method: get
      controller: HomeController
      function: index



# Route Tester
test: 
  path: 
    /test: 
      method: get
      controller: TestController
      function: index
    /test/do/:params: 
      method: get
      controller: TestController
      function: index
